typography_spectrum: 0.11130784428678453
color:
  brandStrength: 0.7908013367559761
  lightness: 0.9155996479094028
  saturation: 0.27601752732880414
  rhythmicContrast: 0.8246249323710799
  brandColors:
    - '#151515'
    - '#7E6423'
    - '#ECCB58'
    - '#FFFFFF'
    - '#800000'
github: true
layout_spectrum: 0.34503379883244634
analytics:
  twitter: 'https://twitter.com/akasha8k'
  google: UA-108885327-1
author:
  email: info@wowdigees.com
  name: Wow Digees Music Group
  url: 'http://wowdigees.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/79fa9662-35ad-4f53-810d-8fff4a828c0b.png
name: wowdigees
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Digital Music Label
    url: 'https://wowdigees.com'
    type: external
title: score to win!
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5055175f-8b1d-491d-ae68-3b609c43b195.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5055175f-8b1d-491d-ae68-3b609c43b195.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/61c43747-a6ad-4be4-bde8-b65681e03013.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/61c43747-a6ad-4be4-bde8-b65681e03013.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/804a6f8a-817c-4921-8e02-fb32638b3dc9.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/804a6f8a-817c-4921-8e02-fb32638b3dc9.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Digital Music Label
purpose:
  - type: contact
    url: 'mailto:statusimperialmusic@gmail.com'
    label: Contact Us
url: 'http://wowdigees.com'
