layout_spectrum: 0.15399650714249524
typography_spectrum: 0.6820999056471531
color:
  brandStrength: 0.01847489201685063
  lightness: 0.9006914532715732
  saturation: 0.17816862219206916
  rhythmicContrast: 0.28341939135675903
  brandColors:
    - '#CFC291'
    - '#FFF6C5'
    - '#A1E8D9'
    - '#FF712C'
    - '#695D46'
github: true
analytics:
  twitter: 'https://twitter.com/akasha8k'
  google: UA-108885327-1
author:
  email: info@wowdigees.com
  name: Wow Digees Music Group
  url: 'http://wowdigees.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/79fa9662-35ad-4f53-810d-8fff4a828c0b.png
name: Wow Digees Music Group
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Digital Music Label
    url: 'https://wowdigees.com'
    type: external
title: Wow Digees
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d248590d-fb5f-4f1e-a2d2-3675bd1f8790.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d248590d-fb5f-4f1e-a2d2-3675bd1f8790.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Digital Music Label
purpose:
  - type: contact
    url: 'mailto:info@wowdigees.com'
    label: Booking & Artist Inquiry
url: 'http://wowdigees.com'
